---
title: "Project 4 main"
author: "Group7"
date: "4/16/2018"
output: html_document
---

# Memory-Based Algorithm

## Load Organized Data

We have already organized data before
```{r}
# You can check code in "MS_Organize.Rmd" in lib
# ms_train <- read.csv("../data/ms_train.csv")
# ms_test <- read.csv("../data/ms_test.csv")
# You can check code in 'movie_organize.Rmd' in lib
# movie_train <- read.csv("../data/movie_train.csv")
# movie_test <- read.csv("../data/movie_test.csv")

```


## Calculate similarity weights 

Pearson Correlation & Vector Similarity & SimRank
```{r}

# Movie

# You can check code in 'pearson_vector.Rmd' in lib
# load("../output/weight/movie_train_pearson.RData")
# load("../output/weight/movie_train_vector.RData")
# For SimRank, due to the time cose of the calculating, we simplify the data into 100*100 dimension. You can check code in 'Movie Simplify for SimRank' and 'SimRank' in lib

 
# MS

# You can check code in 'pearson_vector.Rmd' in lib
# load("../output/weight/ms_train_pearson.RData")
# load("../output/weight/ms_train_vector.RData")


```


## Select neighborhood and Prediction
```{r}
# Movie

# #movie_pearson_threshold
# neighborhood <- weight_thre(movie_train_pearson)
# movie_pearson_threshold <- movie_predict(similarity = movie_train_pearson)
# save(movie_pearson_threshold,file = "movie_pearson_threshold.RData")
# #movie_vector_threshold
# neighborhood <- weight_thre(movie_train_vector)
# movie_vector_threshold <- movie_predict(similarity = movie_train_vector)
# save(movie_vector_threshold,file = "movie_vector_threshold.RData")
# #movie_simrank_threshold
# neighborhood <- weight_thre(movie_train_simrank)
# movie_simrank_threshold <- movie_predict(train = movie_train[1:100,-1],
#                                     test = movie_test[1:100,-1],
#                                     similarity = movie_train_simrank)
# save(movie_simrank_threshold,file = "movie_simrank_threshold.RData")
# 
# #movie_pearson_bestn
# neighborhood <- weight_bestn(movie_train_pearson)
# movie_pearson_bestn <- movie_predict(similarity = movie_train_pearson)
# save(movie_pearson_bestn,file = "movie_pearson_bestn.RData")
# #movie_vector_bestn
# neighborhood <- weight_bestn(movie_train_vector)
# movie_vector_bestn <- movie_predict(similarity = movie_train_vector)
# save(movie_vector_bestn,file = "movie_vector_bestn.RData")
# #movie_simrank_bestn
# neighborhood <- weight_bestn(movie_train_simrank)
# movie_simrank_bestn <- movie_predict(train = movie_train[1:100,-1],
#                                     test = movie_test[1:100,-1],
#                                     similarity = movie_train_simrank)
# save(movie_simrank_bestn,file = "movie_simrank_bestn.RData")
# 
# #movie_pearson_comb
# neighborhood <- weight_comb(movie_train_pearson)
# movie_pearson_comb <- movie_predict(similarity = movie_train_pearson)
# save(movie_pearson_comb,file = "movie_pearson_comb.RData")
# #movie_vector_comb
# neighborhood <- weight_comb(movie_train_vector)
# movie_vector_comb <- movie_predict(similarity = movie_train_vector)
# save(movie_vector_comb,file = "movie_vector_comb.RData")
# #movie_simrank_comb
# neighborhood <- weight_comb(movie_train_simrank)
# movie_simrank_comb <- movie_predict(train = movie_train[1:100,-1],
#                                     test = movie_test[1:100,-1],
#                                     similarity = movie_train_simrank)
# save(movie_simrank_comb,file = "movie_simrank_comb.RData")


# MS
# #ms_pearson_threshold
# neighborhood <- weight_thre(ms_train_pearson)
# ms_pearson_threshold <- ms_predict(train = ms_train[,-1],
#                       test = ms_test[,-1],
#                      similarity = ms_train_pearson,
#                      neighborhood = neighborhood)
# save(ms_pearson_threshold,file = "ms_pearson_threshold.RData")
# #ms_vector_threshold
# neighborhood <- weight_thre(ms_train_vector)
# ms_vector_threshold <- ms_predict(train = ms_train[,-1],
#                      test = ms_test[,-1],
#                      similarity = ms_train_vector,
#                      neighborhood = neighborhood)
# save(ms_vector_threshold,file = "ms_vector_threshold.RData")
# #ms_pearson_bestn
# neighborhood <- weight_bestn(ms_train_pearson)
# ms_pearson_bestn <- ms_predict(train = ms_train[,-1],
#                      test = ms_test[,-1],
#                      similarity = ms_train_pearson,
#                      neighborhood = neighborhood)
# save(ms_pearson_bestn,file = "ms_pearson_bestn.RData")
# #movie_vector_bestn
# neighborhood <- weight_bestn(ms_train_vector)
# ms_vector_bestn <- ms_predict(train = ms_train[,-1],
#                      test = ms_test[,-1],
#                      similarity = ms_train_vector,
#                      neighborhood = neighborhood)
# save(ms_vector_bestn,file = "ms_vector_bestn.RData")
# #ms_pearson_comb
# neighborhood <- weight_comb(ms_train_pearson)
# ms_pearson_comb <- ms_predict(train = ms_train[,-1],
#                      test = ms_test[,-1],
#                      similarity = ms_train_pearson,
#                      neighborhood = neighborhood)
# save(ms_pearson_comb,file = "ms_pearson_comb.RData")
# #movie_vector_comb
# neighborhood <- weight_comb(ms_train_vector)
# ms_vector_comb <- ms_predict(train = ms_train[,-1],
#                      test = ms_test[,-1],
#                      similarity = ms_train_vector,
#                      neighborhood = neighborhood)
# save(ms_vector_comb,file = "ms_vector_comb.RData")
```

## Evaluation for MS
```{r}
R<-function(predict,true,d=0,alpha=10){
  r<-rep(0,nrow(true))
  r_max<-rep(0,nrow(true))
  
  for(a in 1:nrow(true)){
    
    r[a]<-sort(r[a],decreasing = T)
    true[a,]<-sort(true[a,],decreasing = T)
    
    for(j in 1:ncol(true)){
      
      r[a]<-r[a]+max(predict[a,]-d,0)/2^((j-1)/(alpha-1))
      r_max[a]<-r_max[a]+sum(max(true[a,]-d,0)/2^((j-1)/(alpha-1)))
      
    }
  }
  
  rs<-100*sum(r)/sum(r_max)
  return(rs)
}

# load("../output/memory_based_predict/ms/ms_pearson_bestn.RData")
# load("../output/memory_based_predict/ms/ms_pearson_threhold.RData")
# load("../output/memory_based_predict/ms/ms_pearson_comb.RData")
# load("../output/memory_based_predict/ms/ms_vector_bestn.RData")
# load("../output/memory_based_predict/ms/ms_vector_threhold.RData")
# load("../output/memory_based_predict/ms/ms_vector_comb.RData")

# R_ms_pearson_bestn <- R(ms_pearson_bestn, ms_test, 0, 10)
# R_ms_pearson_bestn
# R_ms_pearson_threhold <- R(ms_pearson_threhold, ms_test, 0, 10)
# R_ms_pearson_threhold
# R_ms_pearson_comb <- R(ms_pearson_comb, ms_test, 0, 10)
# R_ms_pearson_comb
# R_ms_vector_bestn <- R(ms_vector_bestn, ms_test, 0, 10)
# R_ms_vector_bestn
# R_ms_vector_threhold <- R(ms_vector_threhold, ms_test, 0, 10)
# R_ms_vector_threhold
# R_ms_vector_comb <- R(ms_vector_comb, ms_test, 0, 10)
# R_ms_vector_comb
```


## Evaluation for Movie
```{r}
options(warn = -1)

# load data
setwd("~/GitHub/Spring2018-Project4-grp7/data")
test <- read.csv("movie_test.csv")
test <- test[,-1]
test2 <- test[1:100,]

setwd("~/GitHub/Spring2018-Project4-grp7/output/memory_based_predict/movie")
load("movie_pearson_threshold.Rdata")
pred_pear_thr <- movie_pearson_threshold
load("movie_vector_threshold.Rdata")
pred_vec_thr <- movie_vector_threshold
load("movie_simrank_threshold.Rdata")
pred_sim_thr <- movie_simrank_threshold

load("movie_pearson_bestn.Rdata")
pred_pear_bn <- movie_pearson_bestn
load("movie_vector_bestn.Rdata")
pred_vec_bn <- movie_vector_bestn
load("movie_simrank_bestn.Rdata")
pred_sim_bn <- movie_simrank_bestn

load("movie_pearson_comb.Rdata")
pred_pear_cb <- movie_pearson_comb
load("movie_vector_comb.Rdata")
pred_vec_cb <- movie_vector_comb
load("movie_simrank_comb.Rdata")
pred_sim_cb <- movie_simrank_comb


## MAE

#function
mae <- function(pred, test){
  mae <- mean(abs(pred - test), na.rm = T)
  return(mae)
}

#output
mae(pred_pear_thr, as.matrix(test))
mae(pred_vec_thr, as.matrix(test))
mae(pred_sim_thr, as.matrix(test2))
mae(pred_pear_bn, as.matrix(test))
mae(pred_vec_bn, as.matrix(test))
mae(pred_sim_bn, as.matrix(test2))
mae(pred_pear_cb, as.matrix(test))
mae(pred_vec_cb, as.matrix(test))
mae(pred_sim_cb, as.matrix(test2))


## ROC

library("pROC")

#function
# remove NA value
test_v_0 <- as.vector(as.matrix(test))
test_v_1 <- as.vector(as.matrix(test2))
idx0 <- which(is.na(test_v_0)==T)
idx1 <- which(is.na(test_v_1)==T)

auc <- function(Pred,Test,Idx){
  pred_v <- as.vector(Pred)
  idx2 <- which(is.na(pred_v)==T)
  idx <- union(Idx,idx2)
  pred_v <- pred_v[setdiff(1:length(Test),idx)]
  test_v <- Test[setdiff(1:length(Test),idx)]
  Roc <- roc(test_v,pred_v)
  return(Roc$auc)
}

curve <- function(Pred,Test,Idx){
  pred_v <- as.vector(Pred)
  idx2 <- which(is.na(pred_v)==T)
  idx <- union(Idx,idx2)
  pred_v <- pred_v[setdiff(1:length(Test),idx)]
  test_v <- Test[setdiff(1:length(Test),idx)]
  Roc <- roc(test_v,pred_v)
  curve <- plot(Roc) 
  return(curve)
}


#output
 
auc(pred_pear_thr,test_v_0,idx0)
curve(pred_pear_thr,test_v_0,idx0)
auc(pred_vec_thr,test_v_0,idx0)
curve(pred_vec_thr,test_v_0,idx0)
auc(pred_sim_thr,test_v_1,idx1)
curve(pred_sim_thr,test_v_1,idx1) 

auc(pred_pear_bn,test_v_0,idx0)
curve(pred_pear_bn,test_v_0,idx0)
auc(pred_vec_bn,test_v_0,idx0)
curve(pred_vec_bn,test_v_0,idx0)
auc(pred_sim_bn,test_v_1,idx1)
curve(pred_sim_bn,test_v_1,idx1) 

auc(pred_pear_cb,test_v_0,idx0)
curve(pred_pear_cb,test_v_0,idx0)
auc(pred_vec_cb,test_v_0,idx0)
curve(pred_vec_cb,test_v_0,idx0)
auc(pred_sim_cb,test_v_1,idx1)
curve(pred_sim_cb,test_v_1,idx1)
```


# Model-Based Algorithm
